FROM apache/airflow:2.8.1-python3.10

USER root
RUN apt-get update && apt-get install -y \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*


USER airflow
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
